"use client";
import { FormEvent, useEffect, useState } from "react";
import { Award, Gift, Loader2, Newspaper, Plus, RefreshCw, Sparkles, Trash2 } from "lucide-react";
import { GULF_CUP_27_TOURNAMENT_ID, type TournamentRewardStatus, type TournamentRewardV2, type TournamentStudioPostCategory, type TournamentStudioPostV2 } from "@/domain/tournaments";
import { deleteTournamentRewardV2, deleteTournamentStudioPostV2, getTournamentAchievementsV2, getTournamentRewardsV2, getTournamentStudioPostsV2, rebuildTournamentAchievementsV2, saveTournamentRewardV2, saveTournamentStudioPostV2 } from "@/lib/tournamentEngagementV2";
import { addAdminLog } from "@/lib/adminLogs";

export default function AdminTournamentEngagementV2(){
 const [posts,setPosts]=useState<TournamentStudioPostV2[]>([]);const[rewards,setRewards]=useState<TournamentRewardV2[]>([]);const[achievementCount,setAchievementCount]=useState(0);const[loading,setLoading]=useState(true);const[working,setWorking]=useState("");const[message,setMessage]=useState("");const[error,setError]=useState("");
 const[postForm,setPostForm]=useState({title:"",summary:"",body:"",category:"news" as TournamentStudioPostCategory,published:true,pinned:false});
 const[rewardForm,setRewardForm]=useState({title:"",description:"",rankFrom:1,rankTo:1,status:"published" as TournamentRewardStatus});
 async function load(){setLoading(true);setError("");try{const[p,r,a]=await Promise.all([getTournamentStudioPostsV2(GULF_CUP_27_TOURNAMENT_ID,true),getTournamentRewardsV2(GULF_CUP_27_TOURNAMENT_ID,true),getTournamentAchievementsV2(GULF_CUP_27_TOURNAMENT_ID)]);setPosts(p);setRewards(r);setAchievementCount(a.length);}catch(e){console.error(e);setError("تعذر تحميل محتوى البطولة");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function addPost(e:FormEvent){e.preventDefault();if(!postForm.title.trim()||!postForm.summary.trim()){setError("أدخل عنوان النشرة وملخصها");return;}setWorking("post");setError("");try{const id=await saveTournamentStudioPostV2({tournamentId:GULF_CUP_27_TOURNAMENT_ID,...postForm});await addAdminLog({action:"other",title:"نشر محتوى استوديو خليجي 27",description:postForm.title,metadata:{id,published:postForm.published}});setPostForm({title:"",summary:"",body:"",category:"news",published:true,pinned:false});setMessage("تم حفظ النشرة.");await load();}catch(e){setError(e instanceof Error?e.message:"تعذر الحفظ");}finally{setWorking("");}}
 async function removePost(id:string){if(!confirm("حذف هذه النشرة؟"))return;setWorking(`post-${id}`);try{await deleteTournamentStudioPostV2(id);await load();}finally{setWorking("");}}
 async function addReward(e:FormEvent){e.preventDefault();if(!rewardForm.title.trim()){setError("أدخل اسم الجائزة");return;}setWorking("reward");setError("");try{const id=await saveTournamentRewardV2({tournamentId:GULF_CUP_27_TOURNAMENT_ID,...rewardForm});await addAdminLog({action:"other",title:"إضافة جائزة لخليجي 27",description:rewardForm.title,metadata:{id}});setRewardForm({title:"",description:"",rankFrom:1,rankTo:1,status:"published"});setMessage("تم حفظ الجائزة.");await load();}catch(e){setError(e instanceof Error?e.message:"تعذر الحفظ");}finally{setWorking("");}}
 async function syncAchievements(){setWorking("achievements");setError("");try{const count=await rebuildTournamentAchievementsV2(GULF_CUP_27_TOURNAMENT_ID);setMessage(`تمت مزامنة ${count} شارة وإنجاز.`);await load();}catch(e){setError(e instanceof Error?e.message:"تعذرت المزامنة");}finally{setWorking("");}}
 return <section className="mt-5 rounded-3xl border border-fuchsia-300/15 bg-fuchsia-300/[0.04] p-4 md:p-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black text-fuchsia-200/70">Engagement V2</p><h3 className="mt-1 text-lg font-black">الاستوديو · الإنجازات · الجوائز</h3></div><button type="button" onClick={()=>void load()} disabled={loading} className="inline-flex min-h-[44px] items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 text-xs font-black"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>تحديث</button></div>
  {(message||error)&&<div role={error?"alert":"status"} aria-live="polite" className={`mt-4 rounded-2xl border p-3 text-sm font-bold ${error?"border-red-300/20 bg-red-400/10 text-red-100":"border-emerald-300/20 bg-emerald-300/10 text-emerald-100"}`}>{error||message}</div>}
  <div className="mt-5 grid gap-4 xl:grid-cols-2">
   <form onSubmit={addPost} className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex items-center gap-2"><Newspaper className="h-5 w-5 text-emerald-200"/><h4 className="font-black">إضافة نشرة للاستوديو</h4></div><div className="mt-4 grid gap-3"><input value={postForm.title} onChange={e=>setPostForm(v=>({...v,title:e.target.value}))} placeholder="عنوان النشرة" className="h-12 rounded-xl border border-white/10 bg-slate-950/60 px-3 font-bold outline-none focus-visible:ring-2 focus-visible:ring-emerald-300"/><input value={postForm.summary} onChange={e=>setPostForm(v=>({...v,summary:e.target.value}))} placeholder="ملخص قصير" className="h-12 rounded-xl border border-white/10 bg-slate-950/60 px-3 font-bold outline-none focus-visible:ring-2 focus-visible:ring-emerald-300"/><textarea value={postForm.body} onChange={e=>setPostForm(v=>({...v,body:e.target.value}))} placeholder="التفاصيل" rows={4} className="rounded-xl border border-white/10 bg-slate-950/60 p-3 font-semibold outline-none focus-visible:ring-2 focus-visible:ring-emerald-300"/><div className="grid gap-2 sm:grid-cols-2"><select value={postForm.category} onChange={e=>setPostForm(v=>({...v,category:e.target.value as TournamentStudioPostCategory}))} className="h-12 rounded-xl border border-white/10 bg-slate-900 px-3 font-bold"><option value="news">خبر</option><option value="analysis">تحليل</option><option value="alert">تنبيه</option><option value="achievement">إنجاز</option></select><div className="flex items-center gap-4 rounded-xl border border-white/10 px-3 text-xs font-black"><label className="flex items-center gap-2"><input type="checkbox" checked={postForm.published} onChange={e=>setPostForm(v=>({...v,published:e.target.checked}))}/>منشورة</label><label className="flex items-center gap-2"><input type="checkbox" checked={postForm.pinned} onChange={e=>setPostForm(v=>({...v,pinned:e.target.checked}))}/>مثبتة</label></div></div><button disabled={working==="post"} className="inline-flex min-h-[46px] items-center justify-center gap-2 rounded-xl bg-emerald-400 px-4 text-sm font-black text-slate-950 disabled:opacity-50">{working==="post"?<Loader2 className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>}حفظ النشرة</button></div></form>
   <form onSubmit={addReward} className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex items-center gap-2"><Gift className="h-5 w-5 text-sky-200"/><h4 className="font-black">إدارة الجوائز</h4></div><div className="mt-4 grid gap-3"><input value={rewardForm.title} onChange={e=>setRewardForm(v=>({...v,title:e.target.value}))} placeholder="اسم الجائزة" className="h-12 rounded-xl border border-white/10 bg-slate-950/60 px-3 font-bold"/><textarea value={rewardForm.description} onChange={e=>setRewardForm(v=>({...v,description:e.target.value}))} placeholder="وصف الجائزة" rows={3} className="rounded-xl border border-white/10 bg-slate-950/60 p-3"/><div className="grid grid-cols-3 gap-2"><input aria-label="من المركز" type="number" min={1} value={rewardForm.rankFrom} onChange={e=>setRewardForm(v=>({...v,rankFrom:Number(e.target.value)}))} className="h-12 rounded-xl border border-white/10 bg-slate-950/60 px-3 text-center"/><input aria-label="إلى المركز" type="number" min={1} value={rewardForm.rankTo} onChange={e=>setRewardForm(v=>({...v,rankTo:Number(e.target.value)}))} className="h-12 rounded-xl border border-white/10 bg-slate-950/60 px-3 text-center"/><select value={rewardForm.status} onChange={e=>setRewardForm(v=>({...v,status:e.target.value as TournamentRewardStatus}))} className="h-12 rounded-xl border border-white/10 bg-slate-900 px-2 text-xs font-bold"><option value="draft">مسودة</option><option value="published">منشورة</option><option value="awarded">تم التسليم</option><option value="closed">مغلقة</option></select></div><button disabled={working==="reward"} className="inline-flex min-h-[46px] items-center justify-center gap-2 rounded-xl bg-sky-400 px-4 text-sm font-black text-slate-950 disabled:opacity-50"><Plus className="h-4 w-4"/>حفظ الجائزة</button></div></form>
  </div>
  <div className="mt-4 grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-black/15 p-4 lg:col-span-2"><h4 className="font-black">النشرات الحالية ({posts.length})</h4><div className="mt-3 grid gap-2">{posts.slice(0,8).map(p=><div key={p.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/[0.07] p-3"><div className="min-w-0"><p className="truncate text-sm font-black">{p.title}</p><p className="text-[10px] font-bold text-white/40">{p.published?"منشورة":"مسودة"}{p.pinned?" · مثبتة":""}</p></div><button type="button" aria-label="حذف النشرة" onClick={()=>void removePost(p.id)} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-red-300/15 bg-red-400/10 text-red-100"><Trash2 className="h-4 w-4"/></button></div>)}</div></div><div className="rounded-2xl border border-amber-300/15 bg-amber-300/[0.05] p-4"><Award className="h-6 w-6 text-amber-200"/><div className="mt-2 text-3xl font-black">{achievementCount}</div><p className="text-xs font-bold text-white/45">شارات ممنوحة حاليًا</p><button type="button" onClick={()=>void syncAchievements()} disabled={working==="achievements"} className="mt-4 inline-flex min-h-[44px] w-full items-center justify-center gap-2 rounded-xl bg-amber-300 px-3 text-xs font-black text-slate-950 disabled:opacity-50">{working==="achievements"?<Loader2 className="h-4 w-4 animate-spin"/>:<Sparkles className="h-4 w-4"/>}مزامنة الإنجازات</button></div></div>
  <div className="mt-4"><h4 className="font-black">الجوائز الحالية ({rewards.length})</h4><div className="mt-2 grid gap-2 md:grid-cols-2">{rewards.map(r=><div key={r.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/[0.07] bg-black/10 p-3"><div><p className="text-sm font-black">{r.title}</p><p className="text-[10px] font-bold text-white/40">المراكز {r.rankFrom}-{r.rankTo} · {r.status}</p></div><button type="button" aria-label="حذف الجائزة" onClick={async()=>{if(confirm("حذف الجائزة؟")){await deleteTournamentRewardV2(r.id);await load();}}} className="flex h-11 w-11 items-center justify-center rounded-xl border border-red-300/15 bg-red-400/10 text-red-100"><Trash2 className="h-4 w-4"/></button></div>)}</div></div>
 </section>;
}
