"use client";
import { useEffect,useState } from "react";
import { Database,Loader2,RefreshCw,Trophy } from "lucide-react";
import AdminTournamentPredictionsManager from "@/components/AdminTournamentPredictionsManager";
import { ASIAN_CUP_2027_MATCHES,ASIAN_CUP_2027_TEAMS,ASIAN_CUP_2027_TOURNAMENT_ID,getAsianCup2027Team } from "@/domain/tournaments";
import { getTournamentMatchesV2,initializeAsianCup2027V2Data,type TournamentMatchRuntimeV2 } from "@/lib/tournamentV2Firestore";
import { addAdminLog } from "@/lib/adminLogs";
const L="ar-SA-u-ca-gregory-nu-latn";
function d(ts:number){return new Intl.DateTimeFormat(L,{weekday:"short",day:"numeric",month:"short",year:"numeric",timeZone:"Asia/Riyadh"}).format(new Date(ts));}
function t(ts:number){return new Intl.DateTimeFormat(L,{hour:"numeric",minute:"2-digit",hour12:true,timeZone:"Asia/Riyadh"}).format(new Date(ts));}
export default function AdminAsianCup2027Panel(){const [matches,setMatches]=useState<TournamentMatchRuntimeV2[]>([]);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");const [page,setPage]=useState(1);async function load(){setMatches(await getTournamentMatchesV2(ASIAN_CUP_2027_TOURNAMENT_ID,{fallback:false}));}useEffect(()=>{void load()},[]);async function init(){setBusy(true);setMsg("");try{const r=await initializeAsianCup2027V2Data();await addAdminLog({action:"other",title:"تهيئة كأس آسيا 2027",description:`تمت تهيئة ${r.teams} منتخبًا و${r.matches} مباراة من الجدول الرسمي.`});setMsg("تمت مزامنة الجدول الرسمي لكأس آسيا 2027 بنجاح.");await load();}finally{setBusy(false)}}const data=matches.length?matches:ASIAN_CUP_2027_MATCHES as readonly TournamentMatchRuntimeV2[];const pages=Math.max(1,Math.ceil(data.length/20));const shown=data.slice((page-1)*20,page*20);return <div className="mt-5 space-y-5">
<section className="rounded-3xl border border-violet-300/20 bg-violet-300/[0.06] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><Trophy className="h-6 w-6 text-violet-200"/><div><p className="text-xs font-black text-violet-200">إدارة البطولة</p><h2 className="text-xl font-black">كأس آسيا السعودية 2027</h2></div></div><div className="flex gap-2"><button onClick={()=>void init()} disabled={busy} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-violet-300 px-4 text-sm font-black text-slate-950 disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Database className="h-4 w-4"/>}مزامنة الجدول الرسمي</button><button onClick={()=>void load()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/10 px-4 text-sm font-black"><RefreshCw className="h-4 w-4"/>تحديث</button></div></div>{msg?<p className="mt-3 text-sm font-bold text-emerald-200">{msg}</p>:null}<div className="mt-4 grid grid-cols-3 gap-3"><div className="rounded-2xl bg-black/15 p-4"><p className="text-xs text-white/50">المنتخبات</p><b className="text-2xl">{ASIAN_CUP_2027_TEAMS.length}</b></div><div className="rounded-2xl bg-black/15 p-4"><p className="text-xs text-white/50">المباريات</p><b className="text-2xl">{data.length}</b></div><div className="rounded-2xl bg-black/15 p-4"><p className="text-xs text-white/50">الملاعب</p><b className="text-2xl">8</b></div></div></section>
<section className="rounded-3xl border border-white/10 bg-slate-950/30 p-4"><h3 className="font-black">الجدول والملاعب</h3><p className="mt-1 text-xs font-bold text-amber-200/80">التواريخ والملاعب معتمدة. وقت بداية كل مباراة يبقى «يحدد لاحقًا» حتى اعتماده رسميًا، ولن يفتح التوقع تلقائيًا قبل ذلك.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-right text-xs"><thead className="text-white/45"><tr><th className="p-3">#</th><th className="p-3">المواجهة</th><th className="p-3">التاريخ</th><th className="p-3">الوقت</th><th className="p-3">الملعب</th><th className="p-3">المدينة</th></tr></thead><tbody>{shown.map(m=><tr key={m.id} className="border-t border-white/[0.06]"><td className="p-3 font-black">{m.officialMatchNumber}</td><td className="p-3 font-black">{getAsianCup2027Team(m.homeTeamId)?.nameAr||m.homeSourceLabel} × {getAsianCup2027Team(m.awayTeamId)?.nameAr||m.awaySourceLabel}</td><td className="p-3">{d(m.kickoffAt)}</td><td className="p-3 text-amber-200">{m.kickoffTimeTbd?"يحدد لاحقًا":t(m.kickoffAt)}</td><td className="p-3">{m.stadium}</td><td className="p-3">{m.city}</td></tr>)}</tbody></table></div>{pages>1?<div className="mt-4 flex justify-center gap-3"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="rounded-xl border border-white/10 px-4 py-2 disabled:opacity-30">السابق</button><span className="py-2 text-xs font-black">{page} من {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)} className="rounded-xl border border-white/10 px-4 py-2 disabled:opacity-30">التالي</button></div>:null}</section>
<AdminTournamentPredictionsManager tournamentId={ASIAN_CUP_2027_TOURNAMENT_ID} tournamentLabel="كأس آسيا 2027" />
</div>}
