import type { ReactNode } from "react";
import { CalendarDays, ScrollText, UsersRound } from "lucide-react";
import GulfCup27CompetitionPanel from "@/components/GulfCup27CompetitionPanel";
import GulfCup27PredictionsPanel from "@/components/GulfCup27PredictionsPanel";
import GulfCup27LeaderboardPanel from "@/components/GulfCup27LeaderboardPanel";
import TournamentSectionPlaceholder from "@/components/tournaments/TournamentSectionPlaceholder";
import GulfCup27StudioPanel from "@/components/GulfCup27StudioPanel";
import TournamentAutomationHeartbeat from "@/components/TournamentAutomationHeartbeat";
import { GULF_CUP_27_KNOCKOUT_DATES, GULF_CUP_27_KNOCKOUT_SCORING_V1, GULF_CUP_27_TOURNAMENT_ID, type Tournament, type TournamentSection } from "@/domain/tournaments";

const DATE_LOCALE = "ar-SA-u-ca-gregory-nu-latn";
function formatDate(timestamp: number) { return new Intl.DateTimeFormat(DATE_LOCALE,{weekday:"long",day:"numeric",month:"long",timeZone:"Asia/Riyadh"}).format(new Date(timestamp)); }
function GulfRulesSection(){const semi=formatDate(GULF_CUP_27_KNOCKOUT_DATES.semiFinalsAt);const final=formatDate(GULF_CUP_27_KNOCKOUT_DATES.finalAt);return <div className="grid gap-3 md:grid-cols-2"><article className="rounded-[22px] border border-white/10 bg-white/[0.055] p-5"><UsersRound className="h-5 w-5 text-[var(--tournament-primary)]"/><h2 className="mt-3 text-lg font-black">نظام البطولة</h2><p className="mt-2 text-sm font-semibold leading-7 text-white/55">مجموعتان، في كل مجموعة أربعة منتخبات، ويتأهل الأول والثاني إلى نصف النهائي.</p></article><article className="rounded-[22px] border border-white/10 bg-white/[0.055] p-5"><CalendarDays className="h-5 w-5 text-[var(--tournament-primary)]"/><h2 className="mt-3 text-lg font-black">الأدوار النهائية</h2><p className="mt-2 text-sm font-semibold leading-7 text-white/55">نصف النهائي: {semi} · النهائي: {final} في جدة.</p></article><article className="rounded-[22px] border border-white/10 bg-white/[0.055] p-5 md:col-span-2"><ScrollText className="h-5 w-5 text-[var(--tournament-accent)]"/><h2 className="mt-3 text-lg font-black">نظام نقاط التوقعات</h2><p className="mt-2 text-sm font-semibold leading-7 text-white/55">في دور المجموعات: بالملي <strong className="text-white">3 نقاط</strong>، والفائز أو التعادل الصحيح <strong className="text-white">نقطة واحدة</strong>. في خروج المغلوب: بالملي <strong className="text-white">{GULF_CUP_27_KNOCKOUT_SCORING_V1.exact}</strong>، الفائز <strong className="text-white">{GULF_CUP_27_KNOCKOUT_SCORING_V1.outcome}</strong>، المتأهل الصحيح <strong className="text-white">{GULF_CUP_27_KNOCKOUT_SCORING_V1.qualified}</strong>، وطريقة التأهل <strong className="text-white">{GULF_CUP_27_KNOCKOUT_SCORING_V1.method}</strong>.</p></article></div>}
export default function TournamentV2Section({tournament,section}:{tournament:Tournament;section:TournamentSection}){if(tournament.id!==GULF_CUP_27_TOURNAMENT_ID)return <TournamentSectionPlaceholder tournament={tournament} section={section}/>;let content:ReactNode;if(section==="matches")content=<GulfCup27CompetitionPanel/>;else if(section==="predictions")content=<GulfCup27PredictionsPanel/>;else if(section==="leaderboard")content=<GulfCup27LeaderboardPanel/>;else if(section==="rules")content=<GulfRulesSection/>;else content=<GulfCup27StudioPanel/>;return <><TournamentAutomationHeartbeat/><div className="mx-auto max-w-7xl px-3 pb-14 pt-1 sm:px-4 md:px-6 md:pb-20">{content}</div></>}
